//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPGLogArrangeTool.resource {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HtmlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TRPGLogArrangeTool.resource.HtmlResource", typeof(HtmlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   .chat.{0} .chatOneLine,.chat.{0} 
        ///span{{
        /// color: {1} ; 
        /// white-space: normal;
        /// word-wrap: break-word;
        ///}} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ChatColor {
            get {
                return ResourceManager.GetString("ChatColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;chatOneLine&quot;&gt;{0}&lt;/div&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivChatArea {
            get {
                return ResourceManager.GetString("DivChatArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;chatTextArea&quot;&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivChatTextArea {
            get {
                return ResourceManager.GetString("DivChatTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;chat {0} right&quot;&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivChatUserETC {
            get {
                return ResourceManager.GetString("DivChatUserETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;chat {0}&quot;&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivChatUserMain {
            get {
                return ResourceManager.GetString("DivChatUserMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;chat {0}  secretChat&quot;&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivChatUserSecret {
            get {
                return ResourceManager.GetString("DivChatUserSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;/div&gt;
        ///&lt;/div&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivEndLine {
            get {
                return ResourceManager.GetString("DivEndLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;icon image_{0} center&quot;&gt;&lt;/div&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivIcon {
            get {
                return ResourceManager.GetString("DivIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;chatinfo&quot;&gt;&lt;span class=&quot;namearea&quot;&gt;{0}&lt;/span&gt; &lt;span class=&quot;tabnamearea&quot;&gt;[{1}]&lt;/span&gt;&lt;/div&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivMainChat {
            get {
                return ResourceManager.GetString("DivMainChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;chatinfo&quot;&gt;&lt;span class=&quot;namearea&quot;&gt;{0}&lt;/span&gt; &lt;span class=&quot;tabnamearea&quot;&gt;[{1}]&lt;/span&gt;&lt;/div&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DivMainChatETC {
            get {
                return ResourceManager.GetString("DivMainChatETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;chatImage_Icon&quot;&gt;
        ///  &lt;img src=&quot;data:image/png;base64,{0}&quot;      alt=&quot;EventImage&quot;&gt;
        ///&lt;/div&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EventCharacter {
            get {
                return ResourceManager.GetString("EventCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;div class=&quot;chatImage&quot;&gt;
        ///  &lt;img src=&quot;data:image/png;base64,{0}&quot;      alt=&quot;EventImage&quot;&gt;
        ///&lt;/div&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EventImage {
            get {
                return ResourceManager.GetString("EventImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;/body&gt;
        ///&lt;/html&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HTMLFooter {
            get {
                return ResourceManager.GetString("HTMLFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ja&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;meta charset=&quot;utf-8&quot;&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///&lt;style&gt;
        ///.icon {
        ///  width: 80px;
        ///  height: 80px;
        ///  margin: 10px;
        ///  background-image: url(&quot;icon.png&quot;);
        ///  background-repeat: no-repeat;
        ///  background-position: center;
        ///  background-size: contain;
        ///}
        ///.chat {
        ///background-color: #F8F8F8;
        ///display: flex;
        ///margin-top: 5px;
        ///margin-bottom: 5px;
        ///}
        ///a.charactorSheet {
        ///text-decoration: none;
        ///}
        ///.chat.right {
        ///text-align: right;
        ///background-color: #CCCCCC;
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HTMLHeader {
            get {
                return ResourceManager.GetString("HTMLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   background-image: url(data:image/png;base64,{0}); に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageData {
            get {
                return ResourceManager.GetString("ImageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   background-repeat: no-repeat;
        ///background-size: contain;
        ///}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Imagefooter {
            get {
                return ResourceManager.GetString("Imagefooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .image_{0}{{ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImageHeader {
            get {
                return ResourceManager.GetString("ImageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringInfoEN {
            get {
                return ResourceManager.GetString("StringInfoEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringInfoJP {
            get {
                return ResourceManager.GetString("StringInfoJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   main に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringMainEN {
            get {
                return ResourceManager.GetString("StringMainEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メイン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringMainJP {
            get {
                return ResourceManager.GetString("StringMainJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   other に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringOtherEN {
            get {
                return ResourceManager.GetString("StringOtherEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   雑談 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringOtherJP {
            get {
                return ResourceManager.GetString("StringOtherJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   secret に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringSecretEN {
            get {
                return ResourceManager.GetString("StringSecretEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   秘匿 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StringSecretJP {
            get {
                return ResourceManager.GetString("StringSecretJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;/style&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string StyleEnd {
            get {
                return ResourceManager.GetString("StyleEnd", resourceCulture);
            }
        }
    }
}
